version: '3.8'
services:
  db:
    image: mysql:5.7.39
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=prisma-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: {}
